name: CI tmate session
on: [push]

# https://github.com/marketplace/actions/debugging-with-tmate

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
