language: python
os: linux
dist: xenial

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.6
      env:
        - BUILD_AND_PUBLISH_DOCS=1
        # Doctr deploy key for bluesky/bluesky.github.io
        - secure: "YBcBYqB5XJZz9JIlPUHIYWJ9asnwhh+5oPCDmtJBa8XkAr+8sg0dCrtcnZUdbWh3lFwTEHVRzWcFKMK7QEYU+gxo+YuKUx1rDrBPDDYXeobup2R+XNMqnqJym7zzffr2jL18MHF+z97fgXta3DhNgTeAniasgi2jK56/XtAVCdVlvfdq+QxQGCMB/L4cQ5CNGNDhfMyhs2H5NiCPazdpMIosLbgTi0CZmTnCt/nbozA//+tC6Ppp5nDroCNGph3aA3bH4Ya05aFaK/mxc4VIXY+jpKj1ROmfA43i2zyGzPy9IEHpCvBzYNGf+MLl2iTbB33xsGh2agclZ5zaSNVJ6CbnV7YmPD0wdwe3XXeHOi+TTU420OWGp2KyriowBphTgJBKoOiwAlnUO1mm21cqFec0xCpiLSw3OwK5oBF33J1ANeBZH0KNV3xhYs+QAypqDnwY7w/sDOHvpGNV7TqRflyOUcTwqB8jDnpbAtxP5XYY8bqd5Il43LJx7Fwj1726fEAQtI9T56IYUxMAU+/kCXTHeOq3u2T01MBgYWNoCgkPf9lcFrLtyWS4gAj5DyeRnASlbEpwTi97w9OrUpwDUI4nN2zo7TrtI63JxnMYSzeZfXguNR7xC/SNYjWWT06UqnrMw76a/ir3hxFz2a4P12pSmhDLGAs9FQT3zpZFUQI="

install:
  # Install conda.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda.
  - conda info -a
  - env | sort -u

  # Update the yaml file with the Python version from Travis env var.
  - sed -i "s/python>=3.6/python=${TRAVIS_PYTHON_VERSION}/g" environment.yml
  - cat environment.yml

  # Create a test conda env from the environment.yml file.
  - export CONDA_ENV="testenv-${TRAVIS_PYTHON_VERSION}"
  - conda env create -n ${CONDA_ENV} --file environment.yml
  - conda activate $CONDA_ENV

  # Validate that we installed the requested Python version.
  - python -c "import os, sys; sysver='.'.join([str(_) for _ in sys.version_info[:2]]); travis_python=os.getenv('TRAVIS_PYTHON_VERSION'); assert sysver==travis_python, f'Installed Python version {sysver} does not match requested Python version on TravisCI {travis_python}'"

  # Install the package itself.
  - pip install -v .

  # Check the list of installed packages.
  - conda list
  - pip list

script:
  # Running tests
  - conda deactivate
  - conda activate $CONDA_ENV
  - py.test -vv --cov=hkl --cov-report term-missing hkl/tests
  - |
    if [ ! -z "${BUILD_AND_PUBLISH_DOCS}" ]; then
        set -e
        # Install deps for building the docs.
        pip install --upgrade -r requirements-doc.txt

        # Build the docs.
        make -C doc/ html

        # Upload the docs to gh-pages.

        # doctr deploy --deploy-repo bluesky/bluesky.github.io --deploy-branch-name master hklpy

        # A fix for doctr-versions-menu:
        pip install pyparsing --upgrade
        DEPLOY_DIR="hklpy/${TRAVIS_TAG:=master}"
        doctr deploy --command=doctr-versions-menu --build-tags --deploy-repo bluesky/bluesky.github.io --deploy-branch-name master ${DEPLOY_DIR}
    fi
