language: python
os: linux
dist: xenial

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - export CONDA_ENV="testenv"

  # Install conda and prepare the test env.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a
  - env | sort -u

  - conda create -n $CONDA_ENV python=$TRAVIS_PYTHON_VERSION --file environment.yml
  - conda activate $CONDA_ENV

  - pip install -v .
  - conda list

script:
  # Running tests
  - conda deactivate
  - conda activate $CONDA_ENV
  - py.test -vv --cov=hkl --cov-report term-missing hkl/tests

after_success:
  - env | sort
  - coveralls
