language: python
os: linux
dist: xenial

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  # Install conda.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda.
  - conda info -a
  - env | sort -u

  # Update the yaml file with the Python version from Travis env var.
  - sed -i "s/python>=3.6.0/python=${TRAVIS_PYTHON_VERSION}/g" environment.yml
  - cat environment.yml

  # Create a test conda env from the environment.yml file.
  - export CONDA_ENV="testenv-${TRAVIS_PYTHON_VERSION}"
  - conda env create -n ${CONDA_ENV} --file environment.yml
  - conda activate $CONDA_ENV

  - pip install -v .
  - conda list

script:
  # Running tests
  - conda deactivate
  - conda activate $CONDA_ENV
  - py.test -vv --cov=hkl --cov-report term-missing hkl/tests

after_success:
  - env | sort
  - coveralls
