language: python

# sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.6

before_install:
  - export CONDA_ENV="testenv"

  - perl --version
  - git fetch --unshallow

  # INSTALL CONDA
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b -p /home/travis/mc"
  - env

  - export PATH=/home/travis/mc/bin:$PATH
  - conda config --set always_yes true
  - conda update conda --yes
  - conda install conda-build anaconda-client jinja2
  - conda config --add channels lightsource2-tag
  - conda config --add channels soft-matter

  # MAKE THE CONDA RECIPE
  - conda create -n $CONDA_ENV python=$TRAVIS_PYTHON_VERSION
  - source activate $CONDA_ENV

install:
  - conda install numpy pyepics prettytable ipython pip
  # install ophyd and the hkl library
  - conda install ophyd gsl
  - conda install pygobject
  - conda install hkl libiconv
  # mkl-random 1.0.1 requires cython, which is not installed.
  - pip install cython
  # keyring 12.0.1 requires secretstorage, which is not installed.
  - pip install secretstorage

  - pip install coveralls pytest pytest-cov
  - python setup.py develop

  # setup some path environment variables for epics
  - export PATH=$PATH:$EPICS_BASE/bin/$EPICS_HOST_ARCH
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$EPICS_BASE/lib/$EPICS_HOST_ARCH"
  - echo "PATH=$PATH"

script:
  # running tests
  - source deactivate
  - source activate $CONDA_ENV
  - conda list
  - py.test -vv --cov=hkl --cov-report term-missing hkl/tests

after_success:
    - env
    - coveralls
