language: python
os: linux
dist: xenial

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - python: 3.6
    - python: 3.7

before_install:
  - export CONDA_ENV="testenv"
  - git fetch --unshallow

  # Install conda and prepare the test env.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash ./miniconda.sh -b -p /home/travis/mc
  - env | sort -u

  - source /home/travis/mc/etc/profile.d/conda.sh

  - conda config --set always_yes true
  - conda update conda --yes
  - conda config --add channels nsls2forge

  - conda create -n $CONDA_ENV python=$TRAVIS_PYTHON_VERSION
  - conda activate $CONDA_ENV

install:
  - conda install numpy prettytable ipython
  - conda install ophyd hkl
  - pip install coveralls pytest pytest-cov
  - pip install -v .

  # setup some path environment variables for epics
  # - export PATH=$PATH:$EPICS_BASE/bin/$EPICS_HOST_ARCH
  # - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$EPICS_BASE/lib/$EPICS_HOST_ARCH"
  # - echo "PATH=$PATH"

script:
  # running tests
  - conda deactivate
  - conda activate $CONDA_ENV
  - conda list
  - py.test -vv --cov=hkl --cov-report term-missing hkl/tests

after_success:
  - env | sort
  - coveralls
