name: hklpy
channels:
  - nsls2forge
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - bluesky
  - hkl
  - ipython
  - numpy
  - ophyd
  - pint
  - pip
  - prettytable
  - pyepics
  - pyRestTable
  - pip:
    - coveralls
    - pytest
    - pytest-cov
