name: Unit Tests with Conda install

on: [push, pull_request]

jobs:

  build:
    env:
      ENV_NAME: hklpy-test-${{ matrix.python-version }}
      PACKAGE: hklpy

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - shell: bash -l {0}
      run: |
        sed -i.bak "s/name: ${PACKAGE}/name: ${ENV_NAME}/g" environment.yml

    - name: Setup Miniconda ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment:
            ${ENV_NAME}
            # conda-test-env-${{ matrix.python-version }}
        auto-update-conda: true
        channel-priority: true
        channels: defaults,conda-forge
        environment-file: environment.yml
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
        use-only-tar-bz2: true  # required for caching

    - shell: bash -l {0}
      run: |
        conda env list

    - shell: bash -l {0}
      run: |
        conda list
        # conda list --name $ENV_NAME

    - shell: bash -l {0}
      run: |
        conda info

    - shell: bash -l {0}
      run: |
        conda config --show-sources

    - shell: bash -l {0}
      run: |
        conda config --show

    - shell: bash -l {0}
      run: |
        printenv | sort

    - name: Test with only pytest
      run: |
        pytest -vvv hkl/tests

    # - name: Install test dependencies
    #   run: |
    #     conda install -y pytest coverage

    # - shell: bash -l {0}
    #   run: |
    #     conda list

    # - name: Test with coverage and pytest
    #   run: |
    #     coverage run --concurrency=thread --parallel-mode -m pytest -vvv
    #     coverage combine
    #     coverage report
